// src/lib/supportDatabase.js
// Comprehensive database of support resources with regions/states

export const SUPPORT_RESOURCES = [
  // Crisis Hotlines - US
  {
    id: "samhsa-helpline",
    name: "SAMHSA National Helpline",
    type: "Crisis Hotline",
    category: "crisis",
    description: "24/7 free, confidential treatment referral and information service for individuals and families facing mental and/or substance use disorders.",
    phone: "1-800-662-4357",
    text: "HELP4U to 435748",
    link: "https://www.samhsa.gov/find-help/national-helpline",
    regions: ["us"],
    states: ["all"],
    tags: ["substance abuse", "mental health", "treatment", "referral", "crisis", "24/7"],
  },
  {
    id: "suicide-prevention",
    name: "988 Suicide & Crisis Lifeline",
    type: "Crisis Hotline",
    category: "crisis",
    description: "24/7 free and confidential support for people in distress, prevention and crisis resources for you or your loved ones.",
    phone: "988",
    text: "988",
    link: "https://988lifeline.org",
    regions: ["us"],
    states: ["all"],
    tags: ["suicide", "crisis", "mental health", "24/7", "prevention"],
  },
  {
    id: "crisis-text-line",
    name: "Crisis Text Line",
    type: "Crisis Support",
    category: "crisis",
    description: "Text HOME to 741741 for 24/7 crisis support. Free, confidential crisis counseling via text message.",
    phone: null,
    text: "HOME to 741741",
    link: "https://www.crisistextline.org",
    regions: ["us", "ca", "uk"],
    states: ["all"],
    tags: ["crisis", "text", "24/7", "mental health", "suicide prevention"],
  },
  {
    id: "trevor-project",
    name: "The Trevor Project",
    type: "Crisis Support",
    category: "crisis",
    description: "24/7 crisis intervention and suicide prevention services for LGBTQ+ young people.",
    phone: "1-866-488-7386",
    text: "START to 678678",
    link: "https://www.thetrevorproject.org",
    regions: ["us"],
    states: ["all"],
    tags: ["lgbtq", "crisis", "suicide prevention", "youth", "24/7"],
  },

  // Rehab Programs - US by State
  {
    id: "hazelden-betty-ford",
    name: "Hazelden Betty Ford Foundation",
    type: "Rehab Program",
    category: "rehab",
    description: "Comprehensive addiction treatment with locations across the US. Evidence-based treatment for substance use disorders.",
    phone: "1-800-257-7810",
    text: null,
    link: "https://www.hazeldenbettyford.org",
    regions: ["us"],
    states: ["CA", "MN", "OR", "IL", "NY", "FL", "CO", "WA"],
    tags: ["rehab", "addiction", "treatment", "inpatient", "outpatient", "alcohol", "drugs"],
  },
  {
    id: "caron-treatment",
    name: "Caron Treatment Centers",
    type: "Rehab Program",
    category: "rehab",
    description: "Non-profit addiction treatment organization offering comprehensive care for adolescents and adults.",
    phone: "1-800-854-6023",
    text: null,
    link: "https://www.caron.org",
    regions: ["us"],
    states: ["PA", "FL", "TX", "GA"],
    tags: ["rehab", "addiction", "treatment", "adolescent", "adult"],
  },
  {
    id: "promises-treatment",
    name: "Promises Treatment Centers",
    type: "Rehab Program",
    category: "rehab",
    description: "Luxury addiction treatment facilities offering personalized care for substance use and co-occurring disorders.",
    phone: "1-844-876-5568",
    text: null,
    link: "https://www.promises.com",
    regions: ["us"],
    states: ["CA", "TX", "FL", "MA"],
    tags: ["rehab", "luxury", "addiction", "dual diagnosis", "mental health"],
  },

  // Financial Assistance - US
  {
    id: "samhsa-grants",
    name: "SAMHSA Grants and Funding",
    type: "Financial Assistance",
    category: "financial",
    description: "Federal grants and funding opportunities for substance abuse and mental health treatment.",
    phone: "1-877-726-4727",
    text: null,
    link: "https://www.samhsa.gov/grants",
    regions: ["us"],
    states: ["all"],
    tags: ["financial", "grants", "funding", "treatment", "assistance"],
  },
  {
    id: "medicaid",
    name: "Medicaid",
    type: "Financial Assistance",
    category: "financial",
    description: "State and federal program providing health coverage for low-income individuals, including mental health and substance abuse treatment.",
    phone: null,
    text: null,
    link: "https://www.medicaid.gov",
    regions: ["us"],
    states: ["all"],
    tags: ["financial", "insurance", "medicaid", "low income", "treatment"],
  },

  // Canada Resources
  {
    id: "canada-crisis",
    name: "Crisis Services Canada",
    type: "Crisis Hotline",
    category: "crisis",
    description: "24/7 national suicide prevention service for Canadians.",
    phone: "1-833-456-4566",
    text: "45645",
    link: "https://www.crisisservicescanada.ca",
    regions: ["ca"],
    states: ["all"],
    tags: ["crisis", "suicide", "canada", "24/7", "mental health"],
  },
  {
    id: "canada-substance",
    name: "Canadian Centre on Substance Use and Addiction",
    type: "Support Organization",
    category: "support",
    description: "National organization providing information and resources on substance use and addiction in Canada.",
    phone: "1-613-235-4048",
    text: null,
    link: "https://www.ccsa.ca",
    regions: ["ca"],
    states: ["all"],
    tags: ["substance abuse", "addiction", "canada", "resources", "information"],
  },

  // UK Resources
  {
    id: "uk-samaritans",
    name: "Samaritans",
    type: "Crisis Hotline",
    category: "crisis",
    description: "24/7 free emotional support for anyone in distress or at risk of suicide across the UK and Ireland.",
    phone: "116 123",
    text: null,
    link: "https://www.samaritans.org",
    regions: ["uk"],
    states: ["all"],
    tags: ["crisis", "suicide", "uk", "24/7", "emotional support"],
  },
  {
    id: "uk-addiction",
    name: "Addiction Recovery Services UK",
    type: "Rehab Program",
    category: "rehab",
    description: "Comprehensive addiction treatment services across the UK, including NHS and private options.",
    phone: "0800 138 4114",
    text: null,
    link: "https://www.addictionrecovery.org.uk",
    regions: ["uk"],
    states: ["all"],
    tags: ["rehab", "addiction", "uk", "treatment", "nhs"],
  },
];

// US States mapping
export const US_STATES = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

// Canadian Provinces
export const CA_PROVINCES = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "YT", name: "Yukon" },
];

// UK Regions
export const UK_REGIONS = [
  { code: "ENG", name: "England" },
  { code: "SCT", name: "Scotland" },
  { code: "WLS", name: "Wales" },
  { code: "NIR", name: "Northern Ireland" },
];

export const REGIONS = {
  us: { name: "United States", states: US_STATES },
  ca: { name: "Canada", states: CA_PROVINCES },
  uk: { name: "United Kingdom", states: UK_REGIONS },
};

