// src/apps/legal/TermsOfServicePage.jsx

import React, { useEffect } from "react";

const content = [
  "🔵 2. WELLNESSCAFE TERMS OF SERVICE",
  "Effective: 2025",
  "Please read these Terms of Service (“Terms”) carefully before using WellnessCafe.",
  "By using the platform, tools, or content, you agree to these Terms.",
  "If you do not agree, you may discontinue use or continue using Guest Mode.",
  "1. Purpose of WellnessCafe",
  "WellnessCafe provides:",
  "Wellness tools",
  "Breathwork and grounding practices",
  "Mindfulness support",
  "Emotional check-ins",
  "Insights and reflections",
  "A Support Hub for community resources",
  "WellnessCafe does NOT provide medical advice, therapy, or crisis intervention.",
  "For emergencies, call your local emergency number or a crisis hotline immediately.",
  "2. Eligibility",
  "You must be 13 years or older to use this platform.",
  "3. Acceptable Use",
  "You agree not to:",
  "Misuse the platform",
  "Attempt to access restricted features",
  "Harm or destabilize the app",
  "Harass or impersonate others",
  "Upload harmful content or scripts",
  "We may suspend or terminate accounts that violate these terms.",
  "4. Accounts & Guest Mode",
  "You can use WellnessCafe:",
  "As a Guest (anonymous)",
  "By creating an account with email",
  "You are responsible for the security of your login credentials.",
  "5. Data Ownership",
  "Everything you write, track, or create in WellnessCafe belongs to you.",
  "You may export or delete your data at any time.",
  "6. No Medical or Clinical Guarantees",
  "WellnessCafe is a wellness companion, not a clinical tool.",
  "We do NOT:",
  "Diagnose",
  "Treat",
  "Provide therapy",
  "Replace professional clinicians",
  "Insights generated by the system are supportive reflections, not medical advice.",
  "7. Availability",
  "We try to provide 24/7 availability but do not guarantee uninterrupted access.",
  "8. Modification or Termination",
  "We may modify features or discontinue parts of the service to improve performance.",
  "We will notify users of significant changes.",
  "9. Limitation of Liability",
  "To the fullest extent permitted by law, WellnessCafe is not liable for:",
  "Loss of data",
  "Service interruptions",
  "Emotional outcomes from journaling or reflective tools",
  "Misuse of the platform",
  "Use the platform responsibly and within your personal comfort level.",
  "10. Governing Law",
  "These Terms are governed by the laws of the United States.",
  "11. Contact",
  "For questions or concerns:",
  "support@wellnesscafe.net",
];

const TermsOfServicePage = () => {
  useEffect(() => {
    document.title = "Terms of Service - WellnessCafe";
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="lux-shell py-10 space-y-8">
        <header className="space-y-3">
          <p className="text-[11px] uppercase tracking-[0.25em] text-muted-foreground">
            WellnessCafe
          </p>
          <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Effective: 2025</p>
        </header>

        <div className="lux-card p-6 space-y-4 text-sm leading-relaxed text-muted-foreground">
          {content.map((paragraph, index) => (
            <p key={index} className="text-foreground/80">
              {paragraph}
            </p>
          ))}
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage;

